"""
Django settings for nabang project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-hqf*sj6158$j73y(%wbf&j&w-5jx4$0vk2d--q+srdujh=zoka"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    'django.contrib.sites',
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "nabang",
    "board",
    "common",
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.kakao',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.naver',
    'social_django', #
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'django.contrib.sites.middleware.CurrentSiteMiddleware',
    'django.middleware.common.CommonMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',  #
]

CSRF_TRUSTED_ORIGINS = ['http://114.205.122.111',
                        'http://localhost',
                        ]

ROOT_URLCONF = "nabang.urls"

from pathlib import Path
BASE_DIR = Path(__file__).resolve().parent.parent

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                'django.template.context_processors.request',
                'social_django.context_processors.backends',  # <-- 끝에 추가
                'social_django.context_processors.login_redirect', # <-- 끝에 추가
            ],
        },
    },
]

WSGI_APPLICATION = "nabang.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'nabang',
#         'USER': 'root',
#         'PASSWORD': 'aivle',
#         'HOST': 'localhost',
#         'PORT': '3306',
#     }
# }
DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': BASE_DIR / "db.sqlite3",
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'nabang_db',
        'USER': 'root',
        'PASSWORD': '1234',  # 본인이 설정한 MySQL 비밀번호로 변경
        'HOST': 'localhost',
        'PORT': '3306',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'nabang_db',
#         'USER': 'bae_db',
#         'PASSWORD': '1q2w3e4rNabang!',
#         'HOST': '127.0.0.1',
#         'PORT': '3306',
#     }
# }



# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'collected_static')
import os
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'nabang', 'static'),
    os.path.join(BASE_DIR, 'nabang', 'templates'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


LOGIN_URL = '/../'  # 로그인이 필요한 경우 리다이렉트할 URL
LOGOUT_URL = '/../'  # 로그아웃이 필요한 경우 리다이렉트할 URL
LOGIN_REDIRECT_URL = '/../'
LOGOUT_REDIRECT_URL = '/../' 

SITE_ID = 11 

AUTHENTICATION_BACKENDS = [
    'allauth.account.auth_backends.AuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',
    'social_core.backends.kakao.KakaoOAuth2',  # <-- 카카오톡
]

SOCIALACCOUNT_LOGIN_ON_GET = True
ACCOUNT_LOGOUT_REDIRECT_URL = 'index'
ACCOUNT_LOGOUT_ON_GET = True 
ACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_AUTO_SIGNUP = False
SOCIALACCOUNT_EMAIL_VERIFICATION='none'

SOCIALACCOUNT_PROVIDERS = {
    'kakao': {
        'APP': {
            'client_id':'be56835380f36db1533c79bddf121f90',
            'secret':'WyB7IO56SnuDWbn9K2J5JHNG0CGHZeu2',
            'SCOPE':[],
        },
        'AUTH_PARAMS': {
            'redirect_uri': 'http://114.205.122.111/accounts/kakao/login/callback/'
        },
        'SITE_ID': 11, 
        'LOGIN_URL' : 'account_login',
        'LOGOUT_URL' : 'account_logout',
        'SIGNUP_URL' : 'account_signup',
        'LOGIN_CALLBACK_URL' : 'socialaccount:kakao_login',
        'LOGOUT_CALLBACK_URL' : 'socialaccount:kakao_logout',
         
    },
    'google': {
        'APP': {
            'client_id': '1077924745345-ov489soltioemnpbllr0gorsf9u2juhs.apps.googleusercontent.com',
            'secret': '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',
            'key': ''
        },
        'SITE_ID': 11, 
    },
    'naver': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'INIT_PARAMS': {'state': 'random_state_string'},
        'FIELDS': [
            'id',
            'email',
            'name',
            'first_name',
            'last_name',
            'profile_image',
        ],
        'EXCHANGE_TOKEN': True,
        'VERIFIED_EMAIL': True,
        'APP': {
            'client_id': 'AwADkUp7vGQQMqdcBcyC',
            'secret': 'mkLMtAaKRQ',
            'key': ''
        },
        'SITE_ID': 11, 
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Session settings
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # 또는 'django.contrib.sessions.backends.cache'
SESSION_COOKIE_NAME = 'nabang_cookie'
SESSION_COOKIE_AGE = 1209600  # 세션의 유효 기간(초 단위), 2주
SESSION_SAVE_EVERY_REQUEST = True


# social-auth-app-django
SOCIAL_AUTH_KAKAO_KEY = 'be56835380f36db1533c79bddf121f90'  # Client ID
SOCIAL_AUTH_KAKAO_SECRET = 'WyB7IO56SnuDWbn9K2J5JHNG0CGHZeu2'  # Secret
SOCIAL_AUTH_KAKAO_REDIRECT_URI = 'http://114.205.122.111/accounts/kakao/login/callback/'  # Redirect URI
SOCIAL_AUTH_KAKAO_SCOPE = []  # Scope
